//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from WebIDL.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="WebIDLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IWebIDLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.webIDL"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWebIDL([NotNull] WebIDLParser.WebIDLContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.definitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinitions([NotNull] WebIDLParser.DefinitionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] WebIDLParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.callbackOrInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallbackOrInterface([NotNull] WebIDLParser.CallbackOrInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.callbackRestOrInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallbackRestOrInterface([NotNull] WebIDLParser.CallbackRestOrInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.interface_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_([NotNull] WebIDLParser.Interface_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_([NotNull] WebIDLParser.Class_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.partial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartial([NotNull] WebIDLParser.PartialContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.partialDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartialDefinition([NotNull] WebIDLParser.PartialDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.partialInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartialInterface([NotNull] WebIDLParser.PartialInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.interfaceMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMembers([NotNull] WebIDLParser.InterfaceMembersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMember([NotNull] WebIDLParser.InterfaceMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.dictionary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionary([NotNull] WebIDLParser.DictionaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.dictionaryMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionaryMembers([NotNull] WebIDLParser.DictionaryMembersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.dictionaryMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionaryMember([NotNull] WebIDLParser.DictionaryMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.required"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequired([NotNull] WebIDLParser.RequiredContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.partialDictionary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartialDictionary([NotNull] WebIDLParser.PartialDictionaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.default_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_([NotNull] WebIDLParser.Default_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultValue([NotNull] WebIDLParser.DefaultValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.inheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInheritance([NotNull] WebIDLParser.InheritanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension([NotNull] WebIDLParser.ExtensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.enum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_([NotNull] WebIDLParser.Enum_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.enumValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueList([NotNull] WebIDLParser.EnumValueListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.enumValueListComma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueListComma([NotNull] WebIDLParser.EnumValueListCommaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.enumValueListString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueListString([NotNull] WebIDLParser.EnumValueListStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.callbackRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallbackRest([NotNull] WebIDLParser.CallbackRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedef([NotNull] WebIDLParser.TypedefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.implementsStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplementsStatement([NotNull] WebIDLParser.ImplementsStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.const_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConst_([NotNull] WebIDLParser.Const_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.constValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstValue([NotNull] WebIDLParser.ConstValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] WebIDLParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] WebIDLParser.FloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.serializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSerializer([NotNull] WebIDLParser.SerializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.serializerRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSerializerRest([NotNull] WebIDLParser.SerializerRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.serializationPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSerializationPattern([NotNull] WebIDLParser.SerializationPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.serializationPatternMap"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSerializationPatternMap([NotNull] WebIDLParser.SerializationPatternMapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.serializationPatternList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSerializationPatternList([NotNull] WebIDLParser.SerializationPatternListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.stringifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringifier([NotNull] WebIDLParser.StringifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.stringifierRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringifierRest([NotNull] WebIDLParser.StringifierRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.staticMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticMember([NotNull] WebIDLParser.StaticMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.staticMemberRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticMemberRest([NotNull] WebIDLParser.StaticMemberRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.readonlyMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadonlyMember([NotNull] WebIDLParser.ReadonlyMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.readonlyMemberRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadonlyMemberRest([NotNull] WebIDLParser.ReadonlyMemberRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.readWriteAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadWriteAttribute([NotNull] WebIDLParser.ReadWriteAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.attributeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeRest([NotNull] WebIDLParser.AttributeRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeName([NotNull] WebIDLParser.AttributeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.attributeNameKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeNameKeyword([NotNull] WebIDLParser.AttributeNameKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.inherit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInherit([NotNull] WebIDLParser.InheritContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.readOnly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadOnly([NotNull] WebIDLParser.ReadOnlyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperation([NotNull] WebIDLParser.OperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.specialOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialOperation([NotNull] WebIDLParser.SpecialOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.specials"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecials([NotNull] WebIDLParser.SpecialsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.special"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecial([NotNull] WebIDLParser.SpecialContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.operationRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationRest([NotNull] WebIDLParser.OperationRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.optionalIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalIdentifier([NotNull] WebIDLParser.OptionalIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] WebIDLParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] WebIDLParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] WebIDLParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.optionalOrRequiredArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalOrRequiredArgument([NotNull] WebIDLParser.OptionalOrRequiredArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.argumentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentName([NotNull] WebIDLParser.ArgumentNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.ellipsis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEllipsis([NotNull] WebIDLParser.EllipsisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.iterable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterable([NotNull] WebIDLParser.IterableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.optionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalType([NotNull] WebIDLParser.OptionalTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.readWriteMaplike"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadWriteMaplike([NotNull] WebIDLParser.ReadWriteMaplikeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.readWriteSetlike"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadWriteSetlike([NotNull] WebIDLParser.ReadWriteSetlikeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.maplikeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaplikeRest([NotNull] WebIDLParser.MaplikeRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.setlikeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetlikeRest([NotNull] WebIDLParser.SetlikeRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeList([NotNull] WebIDLParser.ExtendedAttributeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributes([NotNull] WebIDLParser.ExtendedAttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttribute([NotNull] WebIDLParser.ExtendedAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeRest([NotNull] WebIDLParser.ExtendedAttributeRestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeInner([NotNull] WebIDLParser.ExtendedAttributeInnerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther([NotNull] WebIDLParser.OtherContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.argumentNameKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentNameKeyword([NotNull] WebIDLParser.ArgumentNameKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.otherOrComma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherOrComma([NotNull] WebIDLParser.OtherOrCommaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] WebIDLParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.singleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleType([NotNull] WebIDLParser.SingleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionType([NotNull] WebIDLParser.UnionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.unionMemberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionMemberType([NotNull] WebIDLParser.UnionMemberTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.unionMemberTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionMemberTypes([NotNull] WebIDLParser.UnionMemberTypesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.nonAnyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonAnyType([NotNull] WebIDLParser.NonAnyTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.bufferRelatedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBufferRelatedType([NotNull] WebIDLParser.BufferRelatedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.constType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstType([NotNull] WebIDLParser.ConstTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] WebIDLParser.PrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.unrestrictedFloatType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnrestrictedFloatType([NotNull] WebIDLParser.UnrestrictedFloatTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.floatType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatType([NotNull] WebIDLParser.FloatTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.unsignedIntegerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsignedIntegerType([NotNull] WebIDLParser.UnsignedIntegerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerType([NotNull] WebIDLParser.IntegerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.optionalLong"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalLong([NotNull] WebIDLParser.OptionalLongContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.promiseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPromiseType([NotNull] WebIDLParser.PromiseTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.null_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_([NotNull] WebIDLParser.Null_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] WebIDLParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierList([NotNull] WebIDLParser.IdentifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.identifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiers([NotNull] WebIDLParser.IdentifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeNoArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeNoArgs([NotNull] WebIDLParser.ExtendedAttributeNoArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeArgList([NotNull] WebIDLParser.ExtendedAttributeArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeIdent([NotNull] WebIDLParser.ExtendedAttributeIdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeIdentList([NotNull] WebIDLParser.ExtendedAttributeIdentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="WebIDLParser.extendedAttributeNamedArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedAttributeNamedArgList([NotNull] WebIDLParser.ExtendedAttributeNamedArgListContext context);
}
