//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from WebIDL.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="WebIDLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IWebIDLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.webIDL"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWebIDL([NotNull] WebIDLParser.WebIDLContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.webIDL"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWebIDL([NotNull] WebIDLParser.WebIDLContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.definitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitions([NotNull] WebIDLParser.DefinitionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.definitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitions([NotNull] WebIDLParser.DefinitionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] WebIDLParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] WebIDLParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.callbackOrInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallbackOrInterface([NotNull] WebIDLParser.CallbackOrInterfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.callbackOrInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallbackOrInterface([NotNull] WebIDLParser.CallbackOrInterfaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.callbackRestOrInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallbackRestOrInterface([NotNull] WebIDLParser.CallbackRestOrInterfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.callbackRestOrInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallbackRestOrInterface([NotNull] WebIDLParser.CallbackRestOrInterfaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.interface_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface_([NotNull] WebIDLParser.Interface_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.interface_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface_([NotNull] WebIDLParser.Interface_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_([NotNull] WebIDLParser.Class_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.class_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_([NotNull] WebIDLParser.Class_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartial([NotNull] WebIDLParser.PartialContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartial([NotNull] WebIDLParser.PartialContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partialDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartialDefinition([NotNull] WebIDLParser.PartialDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partialDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartialDefinition([NotNull] WebIDLParser.PartialDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partialInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartialInterface([NotNull] WebIDLParser.PartialInterfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partialInterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartialInterface([NotNull] WebIDLParser.PartialInterfaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.interfaceMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMembers([NotNull] WebIDLParser.InterfaceMembersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.interfaceMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMembers([NotNull] WebIDLParser.InterfaceMembersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMember([NotNull] WebIDLParser.InterfaceMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMember([NotNull] WebIDLParser.InterfaceMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.dictionary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionary([NotNull] WebIDLParser.DictionaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.dictionary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionary([NotNull] WebIDLParser.DictionaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.dictionaryMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionaryMembers([NotNull] WebIDLParser.DictionaryMembersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.dictionaryMembers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionaryMembers([NotNull] WebIDLParser.DictionaryMembersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.dictionaryMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionaryMember([NotNull] WebIDLParser.DictionaryMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.dictionaryMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionaryMember([NotNull] WebIDLParser.DictionaryMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.required"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequired([NotNull] WebIDLParser.RequiredContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.required"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequired([NotNull] WebIDLParser.RequiredContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partialDictionary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartialDictionary([NotNull] WebIDLParser.PartialDictionaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partialDictionary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartialDictionary([NotNull] WebIDLParser.PartialDictionaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.default_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault_([NotNull] WebIDLParser.Default_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.default_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault_([NotNull] WebIDLParser.Default_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultValue([NotNull] WebIDLParser.DefaultValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultValue([NotNull] WebIDLParser.DefaultValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.inheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInheritance([NotNull] WebIDLParser.InheritanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.inheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInheritance([NotNull] WebIDLParser.InheritanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension([NotNull] WebIDLParser.ExtensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension([NotNull] WebIDLParser.ExtensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_([NotNull] WebIDLParser.Enum_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_([NotNull] WebIDLParser.Enum_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enumValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValueList([NotNull] WebIDLParser.EnumValueListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enumValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValueList([NotNull] WebIDLParser.EnumValueListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enumValueListComma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValueListComma([NotNull] WebIDLParser.EnumValueListCommaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enumValueListComma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValueListComma([NotNull] WebIDLParser.EnumValueListCommaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enumValueListString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValueListString([NotNull] WebIDLParser.EnumValueListStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enumValueListString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValueListString([NotNull] WebIDLParser.EnumValueListStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.callbackRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallbackRest([NotNull] WebIDLParser.CallbackRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.callbackRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallbackRest([NotNull] WebIDLParser.CallbackRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedef([NotNull] WebIDLParser.TypedefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.typedef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedef([NotNull] WebIDLParser.TypedefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.implementsStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplementsStatement([NotNull] WebIDLParser.ImplementsStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.implementsStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplementsStatement([NotNull] WebIDLParser.ImplementsStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.const_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst_([NotNull] WebIDLParser.Const_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.const_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst_([NotNull] WebIDLParser.Const_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.constValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstValue([NotNull] WebIDLParser.ConstValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.constValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstValue([NotNull] WebIDLParser.ConstValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanLiteral([NotNull] WebIDLParser.BooleanLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanLiteral([NotNull] WebIDLParser.BooleanLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatLiteral([NotNull] WebIDLParser.FloatLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatLiteral([NotNull] WebIDLParser.FloatLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerializer([NotNull] WebIDLParser.SerializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerializer([NotNull] WebIDLParser.SerializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializerRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerializerRest([NotNull] WebIDLParser.SerializerRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializerRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerializerRest([NotNull] WebIDLParser.SerializerRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializationPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerializationPattern([NotNull] WebIDLParser.SerializationPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializationPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerializationPattern([NotNull] WebIDLParser.SerializationPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializationPatternMap"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerializationPatternMap([NotNull] WebIDLParser.SerializationPatternMapContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializationPatternMap"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerializationPatternMap([NotNull] WebIDLParser.SerializationPatternMapContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializationPatternList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerializationPatternList([NotNull] WebIDLParser.SerializationPatternListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializationPatternList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerializationPatternList([NotNull] WebIDLParser.SerializationPatternListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.stringifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringifier([NotNull] WebIDLParser.StringifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.stringifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringifier([NotNull] WebIDLParser.StringifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.stringifierRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringifierRest([NotNull] WebIDLParser.StringifierRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.stringifierRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringifierRest([NotNull] WebIDLParser.StringifierRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.staticMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticMember([NotNull] WebIDLParser.StaticMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.staticMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticMember([NotNull] WebIDLParser.StaticMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.staticMemberRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticMemberRest([NotNull] WebIDLParser.StaticMemberRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.staticMemberRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticMemberRest([NotNull] WebIDLParser.StaticMemberRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readonlyMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadonlyMember([NotNull] WebIDLParser.ReadonlyMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readonlyMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadonlyMember([NotNull] WebIDLParser.ReadonlyMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readonlyMemberRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadonlyMemberRest([NotNull] WebIDLParser.ReadonlyMemberRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readonlyMemberRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadonlyMemberRest([NotNull] WebIDLParser.ReadonlyMemberRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readWriteAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadWriteAttribute([NotNull] WebIDLParser.ReadWriteAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readWriteAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadWriteAttribute([NotNull] WebIDLParser.ReadWriteAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.attributeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeRest([NotNull] WebIDLParser.AttributeRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.attributeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeRest([NotNull] WebIDLParser.AttributeRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeName([NotNull] WebIDLParser.AttributeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeName([NotNull] WebIDLParser.AttributeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.attributeNameKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeNameKeyword([NotNull] WebIDLParser.AttributeNameKeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.attributeNameKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeNameKeyword([NotNull] WebIDLParser.AttributeNameKeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.inherit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInherit([NotNull] WebIDLParser.InheritContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.inherit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInherit([NotNull] WebIDLParser.InheritContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readOnly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadOnly([NotNull] WebIDLParser.ReadOnlyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readOnly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadOnly([NotNull] WebIDLParser.ReadOnlyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] WebIDLParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] WebIDLParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.specialOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecialOperation([NotNull] WebIDLParser.SpecialOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.specialOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecialOperation([NotNull] WebIDLParser.SpecialOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.specials"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecials([NotNull] WebIDLParser.SpecialsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.specials"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecials([NotNull] WebIDLParser.SpecialsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.special"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecial([NotNull] WebIDLParser.SpecialContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.special"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecial([NotNull] WebIDLParser.SpecialContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.operationRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperationRest([NotNull] WebIDLParser.OperationRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.operationRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperationRest([NotNull] WebIDLParser.OperationRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalIdentifier([NotNull] WebIDLParser.OptionalIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalIdentifier([NotNull] WebIDLParser.OptionalIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] WebIDLParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] WebIDLParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] WebIDLParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] WebIDLParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] WebIDLParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] WebIDLParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalOrRequiredArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalOrRequiredArgument([NotNull] WebIDLParser.OptionalOrRequiredArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalOrRequiredArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalOrRequiredArgument([NotNull] WebIDLParser.OptionalOrRequiredArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argumentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentName([NotNull] WebIDLParser.ArgumentNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argumentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentName([NotNull] WebIDLParser.ArgumentNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.ellipsis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEllipsis([NotNull] WebIDLParser.EllipsisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.ellipsis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEllipsis([NotNull] WebIDLParser.EllipsisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.iterable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIterable([NotNull] WebIDLParser.IterableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.iterable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIterable([NotNull] WebIDLParser.IterableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalType([NotNull] WebIDLParser.OptionalTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalType([NotNull] WebIDLParser.OptionalTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readWriteMaplike"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadWriteMaplike([NotNull] WebIDLParser.ReadWriteMaplikeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readWriteMaplike"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadWriteMaplike([NotNull] WebIDLParser.ReadWriteMaplikeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readWriteSetlike"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadWriteSetlike([NotNull] WebIDLParser.ReadWriteSetlikeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readWriteSetlike"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadWriteSetlike([NotNull] WebIDLParser.ReadWriteSetlikeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.maplikeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaplikeRest([NotNull] WebIDLParser.MaplikeRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.maplikeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaplikeRest([NotNull] WebIDLParser.MaplikeRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.setlikeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetlikeRest([NotNull] WebIDLParser.SetlikeRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.setlikeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetlikeRest([NotNull] WebIDLParser.SetlikeRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeList([NotNull] WebIDLParser.ExtendedAttributeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeList([NotNull] WebIDLParser.ExtendedAttributeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributes([NotNull] WebIDLParser.ExtendedAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributes([NotNull] WebIDLParser.ExtendedAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttribute([NotNull] WebIDLParser.ExtendedAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttribute([NotNull] WebIDLParser.ExtendedAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeRest([NotNull] WebIDLParser.ExtendedAttributeRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeRest([NotNull] WebIDLParser.ExtendedAttributeRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeInner([NotNull] WebIDLParser.ExtendedAttributeInnerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeInner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeInner([NotNull] WebIDLParser.ExtendedAttributeInnerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOther([NotNull] WebIDLParser.OtherContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.other"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOther([NotNull] WebIDLParser.OtherContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argumentNameKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentNameKeyword([NotNull] WebIDLParser.ArgumentNameKeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argumentNameKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentNameKeyword([NotNull] WebIDLParser.ArgumentNameKeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.otherOrComma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOtherOrComma([NotNull] WebIDLParser.OtherOrCommaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.otherOrComma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOtherOrComma([NotNull] WebIDLParser.OtherOrCommaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] WebIDLParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] WebIDLParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.singleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleType([NotNull] WebIDLParser.SingleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.singleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleType([NotNull] WebIDLParser.SingleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionType([NotNull] WebIDLParser.UnionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionType([NotNull] WebIDLParser.UnionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unionMemberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionMemberType([NotNull] WebIDLParser.UnionMemberTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unionMemberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionMemberType([NotNull] WebIDLParser.UnionMemberTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unionMemberTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionMemberTypes([NotNull] WebIDLParser.UnionMemberTypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unionMemberTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionMemberTypes([NotNull] WebIDLParser.UnionMemberTypesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.nonAnyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonAnyType([NotNull] WebIDLParser.NonAnyTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.nonAnyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonAnyType([NotNull] WebIDLParser.NonAnyTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.bufferRelatedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBufferRelatedType([NotNull] WebIDLParser.BufferRelatedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.bufferRelatedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBufferRelatedType([NotNull] WebIDLParser.BufferRelatedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.constType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstType([NotNull] WebIDLParser.ConstTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.constType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstType([NotNull] WebIDLParser.ConstTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] WebIDLParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] WebIDLParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unrestrictedFloatType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnrestrictedFloatType([NotNull] WebIDLParser.UnrestrictedFloatTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unrestrictedFloatType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnrestrictedFloatType([NotNull] WebIDLParser.UnrestrictedFloatTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.floatType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatType([NotNull] WebIDLParser.FloatTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.floatType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatType([NotNull] WebIDLParser.FloatTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unsignedIntegerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsignedIntegerType([NotNull] WebIDLParser.UnsignedIntegerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unsignedIntegerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsignedIntegerType([NotNull] WebIDLParser.UnsignedIntegerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerType([NotNull] WebIDLParser.IntegerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerType([NotNull] WebIDLParser.IntegerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalLong"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalLong([NotNull] WebIDLParser.OptionalLongContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalLong"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalLong([NotNull] WebIDLParser.OptionalLongContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.promiseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPromiseType([NotNull] WebIDLParser.PromiseTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.promiseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPromiseType([NotNull] WebIDLParser.PromiseTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.null_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNull_([NotNull] WebIDLParser.Null_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.null_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNull_([NotNull] WebIDLParser.Null_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnType([NotNull] WebIDLParser.ReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnType([NotNull] WebIDLParser.ReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] WebIDLParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] WebIDLParser.IdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.identifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifiers([NotNull] WebIDLParser.IdentifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.identifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifiers([NotNull] WebIDLParser.IdentifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeNoArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeNoArgs([NotNull] WebIDLParser.ExtendedAttributeNoArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeNoArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeNoArgs([NotNull] WebIDLParser.ExtendedAttributeNoArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeArgList([NotNull] WebIDLParser.ExtendedAttributeArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeArgList([NotNull] WebIDLParser.ExtendedAttributeArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeIdent([NotNull] WebIDLParser.ExtendedAttributeIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeIdent([NotNull] WebIDLParser.ExtendedAttributeIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeIdentList([NotNull] WebIDLParser.ExtendedAttributeIdentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeIdentList([NotNull] WebIDLParser.ExtendedAttributeIdentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeNamedArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedAttributeNamedArgList([NotNull] WebIDLParser.ExtendedAttributeNamedArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeNamedArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedAttributeNamedArgList([NotNull] WebIDLParser.ExtendedAttributeNamedArgListContext context);
}
