//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from WebIDL.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IWebIDLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class WebIDLBaseListener : IWebIDLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.webIDL"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWebIDL([NotNull] WebIDLParser.WebIDLContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.webIDL"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWebIDL([NotNull] WebIDLParser.WebIDLContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.definitions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitions([NotNull] WebIDLParser.DefinitionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.definitions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitions([NotNull] WebIDLParser.DefinitionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] WebIDLParser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] WebIDLParser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.callbackOrInterface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallbackOrInterface([NotNull] WebIDLParser.CallbackOrInterfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.callbackOrInterface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallbackOrInterface([NotNull] WebIDLParser.CallbackOrInterfaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.callbackRestOrInterface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallbackRestOrInterface([NotNull] WebIDLParser.CallbackRestOrInterfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.callbackRestOrInterface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallbackRestOrInterface([NotNull] WebIDLParser.CallbackRestOrInterfaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.interface_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface_([NotNull] WebIDLParser.Interface_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.interface_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface_([NotNull] WebIDLParser.Interface_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.class_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_([NotNull] WebIDLParser.Class_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.class_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_([NotNull] WebIDLParser.Class_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partial"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartial([NotNull] WebIDLParser.PartialContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partial"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartial([NotNull] WebIDLParser.PartialContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partialDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartialDefinition([NotNull] WebIDLParser.PartialDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partialDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartialDefinition([NotNull] WebIDLParser.PartialDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partialInterface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartialInterface([NotNull] WebIDLParser.PartialInterfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partialInterface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartialInterface([NotNull] WebIDLParser.PartialInterfaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.interfaceMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMembers([NotNull] WebIDLParser.InterfaceMembersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.interfaceMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMembers([NotNull] WebIDLParser.InterfaceMembersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.interfaceMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMember([NotNull] WebIDLParser.InterfaceMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.interfaceMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMember([NotNull] WebIDLParser.InterfaceMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.dictionary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictionary([NotNull] WebIDLParser.DictionaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.dictionary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictionary([NotNull] WebIDLParser.DictionaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.dictionaryMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictionaryMembers([NotNull] WebIDLParser.DictionaryMembersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.dictionaryMembers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictionaryMembers([NotNull] WebIDLParser.DictionaryMembersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.dictionaryMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictionaryMember([NotNull] WebIDLParser.DictionaryMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.dictionaryMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictionaryMember([NotNull] WebIDLParser.DictionaryMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.required"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequired([NotNull] WebIDLParser.RequiredContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.required"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequired([NotNull] WebIDLParser.RequiredContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.partialDictionary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartialDictionary([NotNull] WebIDLParser.PartialDictionaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.partialDictionary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartialDictionary([NotNull] WebIDLParser.PartialDictionaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.default_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefault_([NotNull] WebIDLParser.Default_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.default_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefault_([NotNull] WebIDLParser.Default_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultValue([NotNull] WebIDLParser.DefaultValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultValue([NotNull] WebIDLParser.DefaultValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.inheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInheritance([NotNull] WebIDLParser.InheritanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.inheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInheritance([NotNull] WebIDLParser.InheritanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtension([NotNull] WebIDLParser.ExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtension([NotNull] WebIDLParser.ExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_([NotNull] WebIDLParser.Enum_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_([NotNull] WebIDLParser.Enum_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enumValueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValueList([NotNull] WebIDLParser.EnumValueListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enumValueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValueList([NotNull] WebIDLParser.EnumValueListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enumValueListComma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValueListComma([NotNull] WebIDLParser.EnumValueListCommaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enumValueListComma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValueListComma([NotNull] WebIDLParser.EnumValueListCommaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.enumValueListString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValueListString([NotNull] WebIDLParser.EnumValueListStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.enumValueListString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValueListString([NotNull] WebIDLParser.EnumValueListStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.callbackRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallbackRest([NotNull] WebIDLParser.CallbackRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.callbackRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallbackRest([NotNull] WebIDLParser.CallbackRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.typedef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedef([NotNull] WebIDLParser.TypedefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.typedef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedef([NotNull] WebIDLParser.TypedefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.implementsStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementsStatement([NotNull] WebIDLParser.ImplementsStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.implementsStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementsStatement([NotNull] WebIDLParser.ImplementsStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.const_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConst_([NotNull] WebIDLParser.Const_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.const_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConst_([NotNull] WebIDLParser.Const_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.constValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstValue([NotNull] WebIDLParser.ConstValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.constValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstValue([NotNull] WebIDLParser.ConstValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteral([NotNull] WebIDLParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteral([NotNull] WebIDLParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteral([NotNull] WebIDLParser.FloatLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteral([NotNull] WebIDLParser.FloatLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSerializer([NotNull] WebIDLParser.SerializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSerializer([NotNull] WebIDLParser.SerializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializerRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSerializerRest([NotNull] WebIDLParser.SerializerRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializerRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSerializerRest([NotNull] WebIDLParser.SerializerRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializationPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSerializationPattern([NotNull] WebIDLParser.SerializationPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializationPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSerializationPattern([NotNull] WebIDLParser.SerializationPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializationPatternMap"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSerializationPatternMap([NotNull] WebIDLParser.SerializationPatternMapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializationPatternMap"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSerializationPatternMap([NotNull] WebIDLParser.SerializationPatternMapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.serializationPatternList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSerializationPatternList([NotNull] WebIDLParser.SerializationPatternListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.serializationPatternList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSerializationPatternList([NotNull] WebIDLParser.SerializationPatternListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.stringifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringifier([NotNull] WebIDLParser.StringifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.stringifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringifier([NotNull] WebIDLParser.StringifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.stringifierRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringifierRest([NotNull] WebIDLParser.StringifierRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.stringifierRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringifierRest([NotNull] WebIDLParser.StringifierRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.staticMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticMember([NotNull] WebIDLParser.StaticMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.staticMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticMember([NotNull] WebIDLParser.StaticMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.staticMemberRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticMemberRest([NotNull] WebIDLParser.StaticMemberRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.staticMemberRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticMemberRest([NotNull] WebIDLParser.StaticMemberRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readonlyMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadonlyMember([NotNull] WebIDLParser.ReadonlyMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readonlyMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadonlyMember([NotNull] WebIDLParser.ReadonlyMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readonlyMemberRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadonlyMemberRest([NotNull] WebIDLParser.ReadonlyMemberRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readonlyMemberRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadonlyMemberRest([NotNull] WebIDLParser.ReadonlyMemberRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readWriteAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadWriteAttribute([NotNull] WebIDLParser.ReadWriteAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readWriteAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadWriteAttribute([NotNull] WebIDLParser.ReadWriteAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.attributeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeRest([NotNull] WebIDLParser.AttributeRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.attributeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeRest([NotNull] WebIDLParser.AttributeRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.attributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeName([NotNull] WebIDLParser.AttributeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.attributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeName([NotNull] WebIDLParser.AttributeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.attributeNameKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeNameKeyword([NotNull] WebIDLParser.AttributeNameKeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.attributeNameKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeNameKeyword([NotNull] WebIDLParser.AttributeNameKeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.inherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInherit([NotNull] WebIDLParser.InheritContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.inherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInherit([NotNull] WebIDLParser.InheritContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readOnly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadOnly([NotNull] WebIDLParser.ReadOnlyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readOnly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadOnly([NotNull] WebIDLParser.ReadOnlyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] WebIDLParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] WebIDLParser.OperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.specialOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialOperation([NotNull] WebIDLParser.SpecialOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.specialOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialOperation([NotNull] WebIDLParser.SpecialOperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.specials"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecials([NotNull] WebIDLParser.SpecialsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.specials"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecials([NotNull] WebIDLParser.SpecialsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.special"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecial([NotNull] WebIDLParser.SpecialContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.special"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecial([NotNull] WebIDLParser.SpecialContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.operationRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperationRest([NotNull] WebIDLParser.OperationRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.operationRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperationRest([NotNull] WebIDLParser.OperationRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalIdentifier([NotNull] WebIDLParser.OptionalIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalIdentifier([NotNull] WebIDLParser.OptionalIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] WebIDLParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] WebIDLParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] WebIDLParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] WebIDLParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] WebIDLParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] WebIDLParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalOrRequiredArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalOrRequiredArgument([NotNull] WebIDLParser.OptionalOrRequiredArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalOrRequiredArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalOrRequiredArgument([NotNull] WebIDLParser.OptionalOrRequiredArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argumentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentName([NotNull] WebIDLParser.ArgumentNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argumentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentName([NotNull] WebIDLParser.ArgumentNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.ellipsis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEllipsis([NotNull] WebIDLParser.EllipsisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.ellipsis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEllipsis([NotNull] WebIDLParser.EllipsisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.iterable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterable([NotNull] WebIDLParser.IterableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.iterable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterable([NotNull] WebIDLParser.IterableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalType([NotNull] WebIDLParser.OptionalTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalType([NotNull] WebIDLParser.OptionalTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readWriteMaplike"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadWriteMaplike([NotNull] WebIDLParser.ReadWriteMaplikeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readWriteMaplike"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadWriteMaplike([NotNull] WebIDLParser.ReadWriteMaplikeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.readWriteSetlike"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadWriteSetlike([NotNull] WebIDLParser.ReadWriteSetlikeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.readWriteSetlike"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadWriteSetlike([NotNull] WebIDLParser.ReadWriteSetlikeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.maplikeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaplikeRest([NotNull] WebIDLParser.MaplikeRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.maplikeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaplikeRest([NotNull] WebIDLParser.MaplikeRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.setlikeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetlikeRest([NotNull] WebIDLParser.SetlikeRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.setlikeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetlikeRest([NotNull] WebIDLParser.SetlikeRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeList([NotNull] WebIDLParser.ExtendedAttributeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeList([NotNull] WebIDLParser.ExtendedAttributeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributes([NotNull] WebIDLParser.ExtendedAttributesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributes([NotNull] WebIDLParser.ExtendedAttributesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttribute([NotNull] WebIDLParser.ExtendedAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttribute([NotNull] WebIDLParser.ExtendedAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeRest([NotNull] WebIDLParser.ExtendedAttributeRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeRest([NotNull] WebIDLParser.ExtendedAttributeRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeInner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeInner([NotNull] WebIDLParser.ExtendedAttributeInnerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeInner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeInner([NotNull] WebIDLParser.ExtendedAttributeInnerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOther([NotNull] WebIDLParser.OtherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOther([NotNull] WebIDLParser.OtherContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.argumentNameKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentNameKeyword([NotNull] WebIDLParser.ArgumentNameKeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.argumentNameKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentNameKeyword([NotNull] WebIDLParser.ArgumentNameKeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.otherOrComma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOtherOrComma([NotNull] WebIDLParser.OtherOrCommaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.otherOrComma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOtherOrComma([NotNull] WebIDLParser.OtherOrCommaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] WebIDLParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] WebIDLParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.singleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleType([NotNull] WebIDLParser.SingleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.singleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleType([NotNull] WebIDLParser.SingleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionType([NotNull] WebIDLParser.UnionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionType([NotNull] WebIDLParser.UnionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unionMemberType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionMemberType([NotNull] WebIDLParser.UnionMemberTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unionMemberType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionMemberType([NotNull] WebIDLParser.UnionMemberTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unionMemberTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionMemberTypes([NotNull] WebIDLParser.UnionMemberTypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unionMemberTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionMemberTypes([NotNull] WebIDLParser.UnionMemberTypesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.nonAnyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonAnyType([NotNull] WebIDLParser.NonAnyTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.nonAnyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonAnyType([NotNull] WebIDLParser.NonAnyTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.bufferRelatedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBufferRelatedType([NotNull] WebIDLParser.BufferRelatedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.bufferRelatedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBufferRelatedType([NotNull] WebIDLParser.BufferRelatedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.constType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstType([NotNull] WebIDLParser.ConstTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.constType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstType([NotNull] WebIDLParser.ConstTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] WebIDLParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] WebIDLParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unrestrictedFloatType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnrestrictedFloatType([NotNull] WebIDLParser.UnrestrictedFloatTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unrestrictedFloatType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnrestrictedFloatType([NotNull] WebIDLParser.UnrestrictedFloatTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.floatType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatType([NotNull] WebIDLParser.FloatTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.floatType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatType([NotNull] WebIDLParser.FloatTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.unsignedIntegerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsignedIntegerType([NotNull] WebIDLParser.UnsignedIntegerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.unsignedIntegerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsignedIntegerType([NotNull] WebIDLParser.UnsignedIntegerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerType([NotNull] WebIDLParser.IntegerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerType([NotNull] WebIDLParser.IntegerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.optionalLong"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalLong([NotNull] WebIDLParser.OptionalLongContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.optionalLong"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalLong([NotNull] WebIDLParser.OptionalLongContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.promiseType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPromiseType([NotNull] WebIDLParser.PromiseTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.promiseType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPromiseType([NotNull] WebIDLParser.PromiseTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.null_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNull_([NotNull] WebIDLParser.Null_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.null_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNull_([NotNull] WebIDLParser.Null_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnType([NotNull] WebIDLParser.ReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnType([NotNull] WebIDLParser.ReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] WebIDLParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] WebIDLParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.identifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifiers([NotNull] WebIDLParser.IdentifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.identifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifiers([NotNull] WebIDLParser.IdentifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeNoArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeNoArgs([NotNull] WebIDLParser.ExtendedAttributeNoArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeNoArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeNoArgs([NotNull] WebIDLParser.ExtendedAttributeNoArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeArgList([NotNull] WebIDLParser.ExtendedAttributeArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeArgList([NotNull] WebIDLParser.ExtendedAttributeArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeIdent([NotNull] WebIDLParser.ExtendedAttributeIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeIdent([NotNull] WebIDLParser.ExtendedAttributeIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeIdentList([NotNull] WebIDLParser.ExtendedAttributeIdentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeIdentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeIdentList([NotNull] WebIDLParser.ExtendedAttributeIdentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="WebIDLParser.extendedAttributeNamedArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendedAttributeNamedArgList([NotNull] WebIDLParser.ExtendedAttributeNamedArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="WebIDLParser.extendedAttributeNamedArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendedAttributeNamedArgList([NotNull] WebIDLParser.ExtendedAttributeNamedArgListContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
